// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import DatetimeMinController from "./datetime_min_controller"
application.register("datetime-min", DatetimeMinController)

import ModeCapacityController from "./mode_capacity_controller"
application.register("mode-capacity", ModeCapacityController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)